AWSTemplateFormatVersion: '2010-09-09'
Metadata:
  License: Apache-2.0
Description: ''
Parameters:

Resources:
  EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: !Ref 'InstanceType'
      SecurityGroups: [!Ref 'InstanceSecurityGroup']
      KeyName: !Ref 'KeyName'
      ImageId: !Ref 'LatestAmiId'
Outputs:
